<div style="position: fixed; top: 0; left: 0; margin: 20px 10px; padding: 10px; border: 2px solid #536376; background: #eef2f7; color: #536376;">
    <h3 style="font-weight: normal; margin: 0;"><?php echo $this->__('Subject') ?></h3>
    <p><?php echo $this->getData('subject') ?></p>
    <a href="javascript:void(0);" onclick="console.log(this.parentNode.remove())"><?php echo $this->__('Close') ?></a>
</div>
